# Generated by Django 3.0.7 on 2020-09-25 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('birthday', models.DateField(null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(related_name='liked_by', to='scallops_app.User')),
                ('matches', models.ManyToManyField(related_name='_user_matches_+', through='scallops_app.Match', to='scallops_app.User')),
                ('skips', models.ManyToManyField(related_name='_user_skips_+', to='scallops_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('image', models.ImageField(default='/images/avator.jpg', upload_to='images')),
                ('summary', models.TextField(default='Nothing to display')),
                ('interest', models.TextField(default='Nothing to display')),
                ('goals', models.TextField(default='Nothing to display')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scallops_app.User')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_messages', to='scallops_app.User')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='scallops_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='messages',
            field=models.ManyToManyField(related_name='matches', to='scallops_app.Message'),
        ),
        migrations.AddField(
            model_name='match',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match1', to='scallops_app.User'),
        ),
        migrations.AddField(
            model_name='match',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match2', to='scallops_app.User'),
        ),
    ]
