# Generated by Django 3.0.7 on 2020-09-25 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scallops_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/images/avator.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='user',
            name='skips',
            field=models.ManyToManyField(related_name='_user_skips_+', to='scallops_app.User'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scallops_app.User'),
        ),
    ]
