# Generated by Django 3.0.7 on 2020-06-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scallops_app', '0002_auto_20200617_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
