# Generated by Django 3.0.7 on 2020-06-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scallops_app', '0005_user_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(related_name='liked_by', to='scallops_app.User'),
        ),
    ]
