# Generated by Django 3.0.7 on 2020-07-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scallops_app', '0007_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matches',
            field=models.ManyToManyField(related_name='_user_matches_+', to='scallops_app.User'),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
