# Generated by Django 3.0.7 on 2020-07-03 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scallops_app', '0007_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='match',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='scallops_app.Match'),
            preserve_default=False,
        ),
    ]
